### ISSUE TITLE
Pressing "Resume" with the render at or over SPP runs a single sample, then pauses, instead of continuing to render.

### ISSUE THREAD

**Issue by cybergeek94** [llbit/chunky#157]
Last I remember, pressing "Resume" with the render at or over SPP would let it run indefinitely, or until it was manually paused or halted. Now, it runs a single sample and pauses again. Another attempt does the same thing, as does another after that.

Setting the SPP higher works just fine, but this was an interesting feature (intended or otherwise) and it's a bit disappointing that it no longer works.

This is with the current release version (1.1.12). I downloaded the cross-platform binaries and copied the .jar over the existing one to update.

Thanks for the credit, by the way. I'll try to get some commits in this time and not just point out problems.

**Comment by llbit** [comment]
The way it currently works, after some changes since this issue was reported, is that Chunky refuses to render past the target SPP. The resume button becomes disabled, and the only way to continue is to set a new SPP target. It is of course possible to change the target to a very high value and continue rendering practically indefinitely.

I like the current interaction and have no plans to change it so I will mark this as "wontfix" and close the issue.
