### ISSUE TITLE
Volumetric fog doesn't show on stairs

### ISSUE THREAD

**Issue by seaside98** [llbit/chunky#299]
The transparent part of the stair object appears to be blocking volumetric fog.
![seaside16-882](https://cloud.githubusercontent.com/assets/6372893/5794199/30a132fc-9f29-11e4-8320-d6d075de248f.png)

**Comment by llbit** [comment]
Which version of Chunky were you using?

The steps look a little too big for regular stair blocks. Are those regular stairs or half slabs?

**Comment by llbit** [comment]
> Are those regular stairs or half slabs?

After looking at the image a bit more I concluded that the block is a regular oak stair block.

It seems like the voxel intersection point is used for fog calculation rather than the internal intersection point. I set up a test scene to reproduce this issue and I think I can notice it but it is so slight. You must have a modified version of Chunky which has much higher fog density and thus exposing this bug.

**Comment by seaside98** [comment]
My chunky isn't modified; I believe it is visible because the sunlight is coming through the roof at such an angle that it just brushes past the stairs. So no fog is rendered in front of them.

**Comment by llbit** [comment]
It was difficult to set up a scene that had the same effect happen, but when I increase the fog density I get this result, which is based on the same error that causes the problem you noticed:

![fogtest-1000](https://cloud.githubusercontent.com/assets/2757386/6319631/8cd7cae4-bac3-11e4-89cc-e883fd30a933.png)

I should be able to fix this issue now.

**Comment by llbit** [comment]
Fixed! Thank you for reporting this issue! It turned out that only stairs were affected by this bug!

Before:

![fog01](https://cloud.githubusercontent.com/assets/2757386/6319770/b5d21854-bac9-11e4-8824-3c38fc2ec8d5.png)

After:

![fog02](https://cloud.githubusercontent.com/assets/2757386/6319771/b98f7504-bac9-11e4-9780-9ce4bc246f30.png)

**Comment by seaside98** [comment]
Awesome, thanks!






On Sunday, Feb 22, 2015 at 12:34 PM, Jesper Öqvist <notifications@github.com>, wrote:

Closed #299 via 4369784.
