### ISSUE TITLE
Random spots of transparency in png

### ISSUE THREAD

**Issue by seaside98** [llbit/chunky#311]
There are several random splotches of about 50% opacity in the outputted png. They all seem to be either in the water or right next to it. The most obvious one is in the lower right corner, but there are smaller ones in many of the bodies of water. ![retinaseaside](https://cloud.githubusercontent.com/assets/6372893/6701115/2259db5a-cce6-11e4-8dd2-b0fdd453c8c7.png)

**Comment by llbit** [comment]
Do you have the "transparent sky" option enabled for this render?

**Comment by seaside98** [comment]
It is not enabled. I uploaded the backup to dropbox: https://www.dropbox.com/s/ssdhyqtpxh8tdf3/Seaside3.zip?dl=0

**Comment by llbit** [comment]
When I loaded your scene the "transparent sky" checkbox was checked. You can uncheck that option to fix the transparent spots but it will require a render reset because the sky color is set to black when using the option. An alternative is to manually remove the alpha channel in an image editor like Gimp or Photoshop.

**Comment by seaside98** [comment]
Hmm, for whatever reason, it didn't show it as checked. Toggling it fixed the issue. Thanks!
