### ISSUE TITLE
Headless rendering resets sun's position

### ISSUE THREAD

**Issue by haloflooder** [llbit/chunky#321]
The sun's position is different when doing a headless render on a server. All the machines are running on Java 8.

Rendered on 3 different servers, all of them reset the sun's position. Also reviewed the scene on 2 different computers before sending it over to the servers.

Chunky version: 1.3.5
MC Version: 1.8.6

**Comment by jemus42** [comment]
Same issue on Chunky 1.3.5 with MC 1.8.8.

**Comment by jemus42** [comment]
This is not only the case for scenes created in the GUI and the moved to a server, this is also the case for scenes that were partially rendered in the GUI and then continued on a server in headless mode. I thought the issue might had been incorrect scene saving, but now I'm confused.

Example picture with apparently two suns: http://i.wurstmineberg.de/renders/jemsu/ongoing/pm_cathedral_01-2000.png

**Comment by jason-green-io** [comment]
Yup, I can confirm this too.

**Comment by llbit** [comment]
This issue seems to be caused by the sun vectors not being re-calculated after loading the sun settings from JSON data. In the GUI case a different code path was used where eventually the vectors were re-calculated before rendering. Always re-calculating the vectors after loading JSON data should fix this problem.
