### ISSUE TITLE
Headless parallel render 'cuts off' world

### ISSUE THREAD

**Issue by Martyn96** [llbit/chunky#327]
I've noticed that when using parallel mode in headless rendering if the world is close to the camera it gets 'cut off', like this:

![animated-1](https://cloud.githubusercontent.com/assets/5266086/8775288/08176556-2ee7-11e5-9e24-7244c8c9e032.png)
(You can see it happen here too: https://gfycat.com/AshamedJitteryFoxhound#)

I have rendered the exact same scene in the normal client and this did not happen.

**Comment by Martyn96** [comment]
Increasing or decreasing zoom makes no difference:

![animated-1](https://cloud.githubusercontent.com/assets/5266086/8775718/1b6f28e2-2eeb-11e5-996d-7f39126e5a64.png)

It cuts off water from water world mode too:

![animated-1](https://cloud.githubusercontent.com/assets/5266086/8775765/8e2a0ed8-2eeb-11e5-81f1-f62525e27eb6.png)

**Comment by Martyn96** [comment]
Changing the camera pitch moves the 'black void' too:

![animated-1](https://cloud.githubusercontent.com/assets/5266086/8776954/31164644-2ef5-11e5-9d20-9b5251435573.png)
(side view)

![animated-1](https://cloud.githubusercontent.com/assets/5266086/8776958/354cb608-2ef5-11e5-97ea-eb6fb2cffbb5.png)
(~top view)

**Comment by jason-green-io** [comment]
I think it's because the camera only "sees" blocks that are less than 128 blocks away on a plane perpendicular from the center point. If that makes any sense. It'd nice to specify that distance on PARALLEL.

**Comment by llbit** [comment]
It took some time to understand how this bug happened, but the root cause was that the parallel projector was sometimes initialized with the correct world size, and sometimes not, depending on the differing code paths taken during headless initialization and the GUI scene loading. I have fixed the issue now. However, water can still be clipped by the parallel projection when using the water world mode.
