### ISSUE TITLE
Water appears on signs at y=62 and below in water world mode.

### ISSUE THREAD

**Issue by GolonkaSwe** [llbit/chunky#346]
![chunky-watersigns](https://cloud.githubusercontent.com/assets/13326106/11998055/c7e274de-aa8e-11e5-9731-19cc806a1591.jpg)

A block of water appears over signs located at y62 and below, when waterworld is enabled.
Not a huge thing if you are able to live without waterworld in these situations but necessary to mention.

**Comment by llbit** [comment]
Wow, that's an interesting bug! Thank you for reporting it, and sorry for the late response. I will look into it.

**Comment by llbit** [comment]
The bug was caused by the water world mode first filling the octree with water blocks, then expecting them to get replaced. However when a sign block was encountered it simply skipped zeroing out the block id for the corresponding octree position since sign blocks are now in a separate entity BVH, which left an unintentional water block.
