### ISSUE TITLE
Render Preview not showing any chunks

### ISSUE THREAD

**Issue by macjuul** [llbit/chunky#358]
I just installed Chunky and I can't seem to get the world to load. After selecting the chunks and choosing New scene, the Render Preview will open but only shows a white screen with gray lines.

![image](https://cloud.githubusercontent.com/assets/7606171/14313483/35e74e8c-fbf2-11e5-96ec-9848924935f0.png)

Specs:
- Windows 8
- 6GB RAM
- Intel(R) HD Graphics 5500

**Comment by AstroNiklas** [comment]
Have same issue! Worked when I first ran the program yesterday but today I only get the white cordinates in the preview window.  
Win 10
8GB Ram
Geforce GTX 950

**Comment by llbit** [comment]
The problem seems to be that the "Y cutoff" value is set too high. Please take a look at the [Troubleshooting page](http://chunky.llbit.se/troubleshooting.html) for more information.

See also this similar issue: #380 

I will close this issue, but feel free to reply with followup questions if this did not solve the issue!
