### ISSUE TITLE
Redstone wire shows as black block with red X

### ISSUE THREAD

**Issue by Kultman** [llbit/chunky#359]
Started using Chunky from 1.3.7, and hadn't rendered any scenes with redstone wire yet, just did that today. But I only get a black block with a red X across it. Am I doing anything wrong?

**Comment by Rmarsh92** [comment]
Hi Kultman, had this same issue. I think its due to a change with the block in 1.9. My fix (not the best but it works) was to **completely delete** all of my minecraft files apart from the saves and to reinstall the client but only update to 1.8.9. Hope this helps.

**Comment by Kultman** [comment]
Okay, then I know why. Downgrading wont work, I'm rendering scenes frem our Realms world. I guess a fix must be on the way for Chunky then... :)

**Comment by Kultman** [comment]
Funny thing... Only straight lines with redstone have this problem. Crossing or T-shaped intersections are ok... Weird...

**Comment by llbit** [comment]
This is probably caused by a change in how the data value for redstone wire is stored in Minecraft worlds. I will have a look at it, it is probably a simple thing to fix.

**Comment by llbit** [comment]
I checked what is happening here and it turns out that the cause for this bug is that the texture names for redstone dust (wire) have changed.

Before 1.9, texture names for redstone dust were:

* redstone_dust_cross.png
* redstone_dust_cross_overlay.png
* redstone_dust_line.png
* redstone_dust_line_overlay.png

After 1.9, texture names for redstone dust are:

* redstone_dust_dot.png
* redstone_dust_line0.png
* redstone_dust_line1.png
* redstone_dust_overlay.png

This rename means that Chunky no longer recognizes the redstone dust textures and uses its own default textures which includes the red cross texture that indicates a missing texture.

A workaround for the bug is to load a resource pack for pre-1.9 Minecraft. You can even use the 1.8.9 Jar file as the resource pack.

**Comment by llbit** [comment]
Wtf... Minecraft 1.9 rotated `redstone_dust_line{0,1}` with respect to the original `redstone_dust_line` so I can't even use `redstone_dust_line0` as a  simple replacement of `redstone_dust_line`. This will make it difficult to support *both* 1.9 and older versions.

**Comment by Kultman** [comment]
Hmm... seems like they made changes that make no sense.

Ya, workaround works... Guess that'll do for now. Thanks. 

Looking forward to being able to load carts, boats and other items to the world... :)
