### ISSUE TITLE
 can not load anything on Chunky 1.3.8

### ISSUE THREAD

**Issue by Prcmise** [llbit/chunky#366]
Excuse me, why my scene suddenly become a window that in addition to white and gray background coordinates can not see anything else.
 (1.3.3 don’t have this bug, and yesterday when I use 1.3.8, it is operating correctly. Today just run it and BUG sudden appearance)
 My OS: Windows 10 64bit 10586.318
Ps: I just try to download 1.3.5 and run it, Bug still[sad]

**Comment by Prcmise** [comment]
Maybe I have the issue the same as [https://github.com/llbit/chunky/issues/358](url)

**Comment by llbit** [comment]
Hi, I hope your bug resolved itself, but if it did not I suspect that you have to change the "Y cutoff" parameter because you are trying to load chunk data that is below whatever Y cutoff value you currently have set.

This is a common issue. See for example #380 

I'm closing this issue but if you have further questions feel free to post followup comments.
