### ISSUE TITLE
Chunky won't launch

### ISSUE THREAD

**Issue by NightofHunter** [llbit/chunky#367]
I have tried to run Chunky 1.3.8. However it will not start--it just won't do anything. Three months ago I was able to run Chunky just fine. My computer is running 64 bit. Please help.

**Comment by llbit** [comment]
Thank you for reporting the issue. Even though this reply is a bit late it might help others with a similar problem:

Updating the Java installation can break the Chunky launcher, however it should be possible to fix by reinstalling Chunky. If it still does not work, you can try deleting the `chunky-launcher.json` file in your Chunky settings directory - usually `C:/Users/username/.chunky/chunky-launcher.json`. If that does not work, you can try renaming the `.chunky`. That should work like a complete fresh install.

I have rebuilt the launcher, so it may be working better in the upcoming 1.4 release of Chunky.

I'm closing this issue because it is old, but feel free to post follow up comments.
