### ISSUE TITLE
ChunkyDeployer.java ignores JVM arguments when launching chunky process

### ISSUE THREAD

**Issue by XepherX** [llbit/chunky#371]
Using JVM arguments, you can configure the chunky launcher to be self-contained and sit in a single directory. This behavior is achieved with the following JVM flags:

-Duser.dir=C:/test
-Duser.home=C:/test

which would result in all required libraries being downloaded into the C:/test drive. 

![image](https://cloud.githubusercontent.com/assets/1978472/16348692/77a614ac-3a54-11e6-9aa1-b6b723cb8030.png)

The next step would be downloading minecraft, [as per the Headless Rendering guide](http://chunky.llbit.se/headless.html). Here is where the issue becomes appearant. Due to the fact that the chunky process itself is launched without JVM arguments (my claim is based on the [launchChunky method here.](https://github.com/llbit/chunky/blob/dd105c0f074d528a8395b080f8e1efc57af943ca/launcher/src/se/llbit/chunky/launcher/ChunkyDeployer.java#L238)), chunky now tries to download minecraft into the default %USERPROFILE%/.chunky location, which doesn't exist at this point in time, resulting in File not found (The system cannot find the path specified)

**Comment by llbit** [comment]
Thank you for reporting this issue, it certainly seems like an important use case for headless rendering!

The system properties "user.dir" and "user.home" are not passed through to the launched Chunky process, but instead of doing that I have added support for specifying a different settings directory using the "chunky.home" system variable.

Here is an example of using the new system property to specify a nonstandard settings directory:

```
$ java -Dchunky.home="C:\\Users\\jesper\\test" -jar build/chunky-1.3.8-21-g9805732.jar -download-mc 1.10.2
Warning: Could not load settings from C:\Users\jesper\test\chunky.json - defaults will be used
Warning: Could not load settings from C:\Users\jesper\test\chunky-launcher.json - defaults will be used
Warning: Could not load settings from C:\Users\jesper\test\chunky.json - defaults will be used
Downloading Minecraft 1.10.2...
url: https://s3.amazonaws.com/Minecraft.Download/versions/1.10.2/1.10.2.jar
destination: C:\Users\jesper\test\resources\minecraft.jar
Done!
```

Note that I ran in Bash Git on Windows where it is necessary to escape the backslashes, it may not be necessary in the default Windows command line. If you want to avoid the warning messages you can just copy the settings files from a previous Chunky installation.

I will update the Wiki with these instructions on the headless rendering page.

**Comment by XepherX** [comment]
I know I'm a bit late, but kudos for implementing it promptly! I just tested it the other day, and it worked flawlessly. Thanks!
