### ISSUE TITLE
Creating scenes in headless mode

### ISSUE THREAD

**Issue by RobertHerhold** [llbit/chunky#372]
Is it possible to create scenes in headless mode, or does it only render already existing scenes?

**Comment by empirebuilder1** [comment]
Please use the dedicated [Chunky subreddit](https://www.reddit.com/r/chunky) for questions.  

As far as I know, it's only possible to create scenes in the GUI version of the program.

**Comment by llbit** [comment]
It is not possible to create a new scene from the command line. If you have an existing scene you can copy it and modify the [scene description file](http://chunky.llbit.se/scene_format.html).

There are no plans to support creating a scene from the command line because there are so many scene parameters that can be tweaked to setup a new scene, and the default parameters are not likely to be useful.
