### ISSUE TITLE
A few suggestions. 

### ISSUE THREAD

**Issue by NJDaeger** [llbit/chunky#379]
- An option to hide the sun, sometimes when I render things. I cant see the sun when looking into the clouds, but when I look in reflections I can see the sun perfectly. Could you add an option to disable the sun texture, but still have the sun there? heres an example of this issue: http://i.imgur.com/zr6uzIK.png

- Some type of blending with fog and land. I mean like when you raise the fog strength on a render you can see that the fog got more dense, only on surfaces. The sky doesnt have any fog really. Heres an example: http://i.imgur.com/aZ2LMbT.png (its kinda hard to see, but if you look at the sky compared to the rest of the fog area, you can see the sky has little to no fog coverage)

- A nighttime option? Or the ability to change the sun into the moon. 

I probably have more I just cant think of them off the top of my head as of right now. Otherwise, thank you!

**Comment by llbit** [comment]
Making the Sun invisible has been requested before and it might be added, but is not a high priority.

The fog and sky is tricky because there is no right solution. The only right solution is to do a full atmospheric simulation but that would be too slow to render and less flexible for achieving artistic effects. This is analogous to many other things in Chunky where there is a trade-off between realism and performance and artistic freedom. You can't have all three at the same time.

Night mode would be a very nice addition. Also I would like to have a way for setting lighting and time-of-day presets so that you could select some nice default settings.

Thank you for the suggestions!
