### ISSUE TITLE
Error when target SPP autosave is reached 

### ISSUE THREAD

**Issue by empirebuilder1** [llbit/chunky#390]
I was creating a quick render to test out 1.4.0. I made a scene and set a few basic parameters, and then set the SPP target to 500 and left it for a while. When I came back, it produced [these two errors.](http://i.imgur.com/IlGlHWS.png)  

Seems like it's not creating the files and directories properly, as I can't save the scene file either, although manually saving the render PNG to a different folder works as expected. When I look at .chunky, there is no scenes folder created. 

Should also note this is in Ubuntu 14.04, I haven't tested it in Windows yet.

**Comment by llbit** [comment]
I was able to reproduce this issue. It seems to affect all fresh Chunky installs, which is very unfortunate.

A workaround for the issue is to manually create the directory which the warning dialogs complain about, and then manually save the scene.

I've fixed the issue but will leave the issue open until the next release so hopefully other people who have the same issue see this.
