### ISSUE TITLE
Thread command line option is broken

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#393]
Whenever I start chunky and specify a thread count, e.g. `java -jar chunky.jar -scene-dir /home/maik/scene -render scene -threads 4 -target 1000`, chunky doesn't start and shows `Unrecognized option: 10`.
This occurs as of 1.4.0.

Edit: I just looked at the command line options code... Why are you parsing the arguments by hand? Looks like you re-invented the wheel. :smile:

Edit²: Strange... it seems like the order of the arguments is important. `-render ... -scene-dir` works while `-scene-dir ... -render ...` doesn't.

**Comment by llbit** [comment]
The bug is on [this line](https://github.com/llbit/chunky/blob/master/chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java#L377). The index variable should not be incremented because the option handler is responsible for calculating the next index. This leads to the third command-line argument being skipped in the argument parsing.

>Edit: I just looked at the command line options code... Why are you parsing the arguments by hand? Looks like you re-invented the wheel. 

There are several reasons. I still treat Chunky as my hobby project, and I tend not to use libraries in my hobby projects because it is a very good educational exercise to write everything on your own. Besides that there are some benefits to not using libraries, for example:

* Reduced binary size.
* Full control over the implementation.
* Faster builds.
* Self-contained source code.

Chunky right now only uses one library: Apache Commons Math. If there is not a very strong reason to add a library I will avoid it.

I don't have anything against libraries though, and it makes a lot of sense to use them. Benefits of using libraries include:

* (Hopefully) Well-tested implementation.
* Reduces the complexity of the code you have to maintain.
* Farming out bugs to library owners.

**Comment by AEnterprise** [comment]
the way i've handled command line arguments myself in the past is with a hashmap, that can eighter map to an function/lambada if you use java 8, if not just an object with an apply function will do the trick

it might not be the fasted way to do it but it's run once on startup and it's definatly very easy

**Comment by leMaik** [comment]
@llbit Thanks for fixing this! :+1: Whether to use libraries or not is a matter of taste, but bugs like this one would probably not occur with a (well tested) command line library, which is why I mentioned it. However, you indeed learn a lot by doing things manually instead of just puzzling libraries together.
