### ISSUE TITLE
chunky-core snapshots missing in Sonatype repo

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#397]
For some reason, the snapshots of Chunky 1.4.1 are not available from Sonatype OSS repo anymore. Could you please re-upload them so that developing plugins is a little more convenient? :)

**Comment by llbit** [comment]
If you use Gradle you can clone Chunky and run `git tag -a 1.4.1-snapshot -m "Snapshot" && gradle install` in the Chunky directory to install the snapshot in your local Maven repository.

**Comment by leMaik** [comment]
Thank you. I'd like to have _just type mvn package and you are good to go_ experience, though. That's why I'd like to see chunky in Sonatype OSS or Maven Central repo.

@llbit Would you be okay if I redeploy Chunky in my own public Maven repo? I know it's GPLv3, but I want your opinion on that. :)

**Comment by llbit** [comment]
I have uploaded a 1.4.1 snapshot to the Sonatype repo now. I will probably make this automated so that it builds and uploads every night, but right now I have to manually update the snapshot.

I would request that you upload Chunky under a different name. I prefer if only the builds I have published are visible on this search page: http://search.maven.org/#search%7Cga%7C1%7Cchunky

**Comment by leMaik** [comment]
Allright, the snapshot makes a re-upload obsolete. Thank you! :+1:
I wouldn't have it published to the Maven Central but to my own repo, though, so the search results wouldn't be affected anyway.

**Comment by llbit** [comment]
Oh, well feel free to use your own Maven repository. I only care about the central repo.
