### ISSUE TITLE
Chunky ignores skymap loading errors

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#398]
When using the headless renderer and loading a hdr skymap fails (due to an invalid file), the rendering is continued without a skymap because the exception is ignored (only logged). I'd like Chunky to terminate with a non-zero exit code in this case, as I wouldn't like to spend hours for rendering a broken image anymore. :)

**Comment by AEnterprise** [comment]
maybe have it do that with anything that logs and exception? there could be another run argument to let it ignore it but having it render with things that might affect the rendering could potentially ruin the entire image, forcing you to start from scratch

**Comment by llbit** [comment]
When using the GUI, I think it is reasonable to expect that the user wants to load a different skymap if the saved one failed to load. However, in headless mode it is clearly a bad idea to try to render a scene with the wrong skymap.

I tried to improve error handling for skymap loading errors in Chunky. I changed all skymap loading warnings into a errors. If any error occurs during scene loading a headless render will now abort with the following message:

>Aborting render due to errors while loading the scene.
>Run again with -f to render anyway.

There was also an oversight in the skymap loading code that caused it to not generate any warning or error at all if the skymap file did not exist.

There are still some improvements that can be made, for example the GUI does not clearly show that an error occured while loading the current scene. Because the default error dialog is not connected to any particular scene, it might be difficult to see why any error occurred.

Another possible improvement is to use a separate logging receiver for each scene loading job, so that scene loading errors are clearly separated from other error sources.

Finally, it would be nice if headless rendering could be aborted before loading the octree and render dump if the skymap fails to load. Currently it only aborts after attempting to load everything.
