### ISSUE TITLE
suggestion to efficiently reduce noise in low light areas

### ISSUE THREAD

**Issue by ricsonc** [llbit/chunky#432]
it looks like the same amount of samples is used for every pixel in the image.
i suspect for many renders, especially those where parts of the image are in low light, the variance of the samples of most pixels will be low, and the variance of pixels in darker areas will be high.

therefore, could the rendering algorithm be improved by using a dynamic number of samples per location? once the variance of a pixel was below a certain threshold, we could stop getting samples for that pixel, speeding computation up. 

edit: [i found pretty much the same idea in the literature](https://books.google.com/books?id=YPblYyLqBM4C&pg=PA242&lpg=PA242&dq=ray+tracing+variance+computation&source=bl&ots=y_e9VBmhQ9&sig=r4PJxiq40eub1fuTFh0yoq5GPqY&hl=en&sa=X&ved=0ahUKEwiQ1_rAzM3UAhVXzGMKHcA8DW8Q6AEIRDAE#v=onepage&q=ray%20tracing%20variance%20computation&f=false)

**Comment by llbit** [comment]
I had the same idea a few years ago and implemented a simple version of it in Chunky. The results were not very good. The problem is that it gives a small improvement but increases rendering time overall. You have to make a very efficient variance estimator for it to pay off in practice. You also lose some efficiency in the more complex work balancing that needs to be done.

I read [this related paper](https://link.springer.com/chapter/10.1007/978-3-7091-6858-5_26) when I implemented this in Chunky, and if I recall correctly they had similar results.
