### ISSUE TITLE
Minecraft 1.12 support

### ISSUE THREAD

**Issue by NoahLiedFilmSchool** [llbit/chunky#442]
Is the newest chunky 1.12 support?

I want a hq image of my 1.12 world rendered with shaders.

**Comment by chland** [comment]
The latest version supports MC 1.12 but has some issues with walls/fences at the moment but llbit is working hard on fixing them.

**Comment by kiddailey** [comment]
There is also an issue with the newer blocks (e.g. concrete), where they are visible on the overhead map but do not preview or render.  As long as you're not using the newer blocks though, it seems to work pretty well.  There is already a separate issue  (#429) for this bug.

**Comment by llbit** [comment]
@kiddailey Concrete blocks are rendered fine for me in version 1.4.3. What version of Chunky are you using?

**Comment by llbit** [comment]
Closing this because it should be fixed now in version 1.4.3. Please re-open/comment if you find any bugs. Thanks!

**Comment by llbit** [comment]
Minecraft 1.12 beds are not fully supported yet (see #433 and #443). They will be fixed in the next version.

**Comment by kiddailey** [comment]
@llbit I was clarifying with additional information for the OP since they did not state which version they were referring to.  I was referring to 1.4.2 since [the website is still linking to that as the current release.](http://chunky.llbit.se/download.html)  I hadn't seen the announcement on Reddit when I posted (oops) :)

Yes, the 1.4.3 snapshot resolves the issue, which I mentioned on the #429 issue :)  Thanks for the awesome software and responses.  Apologies for the extra chatter and notifications.
