### ISSUE TITLE
Minor bugs/suggestions (win7x64 if that matters)

### ISSUE THREAD

**Issue by ComputerJock** [llbit/chunky#444]
1. I like chunky!

2, PNG's are missing the 'IEND' chunk. Many image viewers throw an error and refuse to load the image. The fix is simple: just add the IEND chunk to the PNG. An 'IEND' chunk always has the same format:

byte iendData[] = {
	(byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x49, (byte)0x45,
	(byte)0x4E, (byte)0x44, (byte)0xAE, (byte)0x42, (byte)0x60, (byte)0x82
};

3. Please remember the last folder used for a PNG save. 
4. Please make sure a filename ends with the '.png' extension
5. When the chunks tab window is minimized and then unminimized, the right side of the screen (with the tabs) expands to more than 1/2 of the screen width thus shrinking the map image on the left. If possible, it would be nice if the right side only took as much space as needed. FYI, my screen size is 1920x1080.
6. When I open the scene tab, take all defaults and press "render" then all I get is a blank, gray image. It would be nice if the default parameters would result in an actual image so I could tweak things and learn what they do.

7. It would be nice if there was a way to dump a grid of the entire world as NxN PNG's -- one could then stitch them together (yes, I know the result would be a really big image but I have 16G memory and I'd like to use it)

Thanks for reading.

**Comment by llbit** [comment]
Thanks for the bug report and suggestions. The PNG IEND issue should be fixed in the next snapshot/release.

Regarding saving the whole map as a PNG: that feature is outside the scope for Chunky. I think there are other programs that do that better. Chunky is more commonly used for 3D rendering. The reason it is possible to save the visible 2D map is because that feature was almost free to implement. However, it would require a large amount of work to make a solid implementation of whole-world 2D map rendering. For example, the map would ideally be loaded and rendered incrementally, which would require some major architectural changes.
