### ISSUE TITLE
[1.4.4-a2] Y-Cutoff causes strange stone-grid

### ISSUE THREAD

**Issue by chland** [llbit/chunky#448]
I noticed something very odd while using Y-Cutoff. I created a Flatword with the desert-preset (8 layers of sand, 52 layers of sandstone, etc.) and then set the "Y clip max" to 63 and thats what happened:

![cutoff_bug](https://user-images.githubusercontent.com/472894/28924125-e5616f46-7860-11e7-80cc-68d116460314.jpg)

The chunk-borders are still sand but on the inside they are filled with stone!???? The same happens for normal worlds:

![cutoff_bug_2](https://user-images.githubusercontent.com/472894/28924345-acac3892-7861-11e7-8b14-eaa99c425818.jpg)

It guess thats caused by some kind of octree-optimization you're doing? As it looks like stone is at all those places that are usually not visible?

**Comment by llbit** [comment]
You are right! You have discovered a small optimization that I do to reduce the octree size. 
The ground in Minecraft worlds is normally filled by small gravel patches and various ores. These small structures break up an otherwise invisible part of the octree into unnecessary pieces, increasing the memory use. Octrees are otherwise very good at compressing large uniform structures. To fix this I try to set all normally-invisible blocks to stone to reduce the number of internal octree nodes. Stone is used because it is assumed to be one of the most common block types near invisible regions.

However, the octree construction works per-chunk, so it is not easy to test if the blocks on a chunk border are visible. Therefore, I set all edge blocks to visible and they retain their original block type. So that explains the grid pattern you see.

The you can see the grid pattern when using the Y clamping setting is because there is an extra condition that tests if a block is at the top or bottom of a chunk. These blocks are always visible. However, I did not update these checks when implementing Y clamping so now it is assumed that normally-invisible chunks are invisible even when exposed due to the Y cutoff.

The relevant lines of code are:

             if (cx > 0 && cx < 15 && cz > 0 && cz < 15 && cy > 0 && cy < 255 &&
                  blockId != Block.STONE_ID && block.opaque) {

                // Set obscured blocks to stone. This makes adjacent obscured
                // blocks be able to be merged into larger octree nodes
                // even if they had different block types originally.
                ....

The relevant part is `cy > 0 && cy < 255`, which should be changed to `cy > yMin && cy < yMax`.

Now that you brought this up, I realize that it is much better to do proper invisibility checking on the edge blocks to avoid that grid pattern. The grid pattern won't work too nicely with the octree.
