### ISSUE TITLE
Black pixel errors 1.4.5

### ISSUE THREAD

**Issue by Consue** [llbit/chunky#479]
Hey so I tried to make water emetite light (bright idea I know) but I keep getting these weird pitch back pixels.
[A gif demo](https://gyazo.com/cb2f0a765c51dc3eff703b2c20cf6431)

**Comment by llbit** [comment]
I tried to reproduce the issue by copying your settings, but I don't get any out of place black pixels.

It's very hard to know what is causing the issue if I can't recreate it. It could be a certain type of block in your scene that causes the problem, though it seems like your scene only has the most common block types. The issue might also be caused by the texture pack you are using. Which texture pack were you using for that scene?

If you can, it would be very helpful if you can send the scene to me.

**Comment by jackjt8** [comment]
**Versions:** `1.4.5`, `2.0-beta6`, `leMaik 246`
**Plugins:** All disabled

If Water Visibility is set to 0 and Water Opacity is not equal to 1 when rendered we get some strange behaviour; Not only is water rendered black but it appears to act like a black hole producing pure black noise.

![0-0](https://user-images.githubusercontent.com/3740917/79055989-a91e1800-7c49-11ea-8a74-3b492e33fd96.png)

This issue can also persist through raising Water Visibility and Water Opacity and multiple uses of the scene `Reset` button, the following is done with 0.1 Visibility and 0.2 Opacity:

![image](https://user-images.githubusercontent.com/3740917/79056054-54c76800-7c4a-11ea-804e-cc5c6f72848b.png)

The following video also showcases the black noise accumulating over multiple changes to the water opacity (all resetting the samples). This is not a graphic glitch and can be seen within the outputted png.

[Youtube Video](https://youtu.be/-eDuGFvxNxo)

Example scene, black noise should also be present: 
[scenes.zip](https://github.com/llbit/chunky/files/4465611/scenes.zip)

---

It is unknown if this is the same cause but hopefully the fix will apply to both.
