### ISSUE TITLE
Allow export for rendering in other programs

### ISSUE THREAD

**Issue by naikrovek** [llbit/chunky#480]
Suggestion

If you aren't going to support GPU path tracing anytime soon, would you consider supporting scene export so users can use a GPU accelerated path tracing renderer other than Chunky?

**Comment by chland** [comment]
If you want to use a different renderer you can always use Mineways to export a scene and import it into Blender, 3DS MAX, Maya or Cinema 4D,

**Comment by naikrovek** [comment]
I did not know that, thank you.

**Comment by llbit** [comment]
Part of the reason why it is not easy to export Chunky scenes to common 3D formats is because we use a nonstandard representation for many block models and custom code would need to be written for each of those custom block renderers to export them to standard triangular mesh data. If/when we migrate to using a fully block-model based renderer (which uses Minecraft resource packs to load all models) this could be done much easier.

**Comment by naikrovek** [comment]
Thanks for the responses, everyone.  I'll close this because my (non-)issue is resolved.
