### ISSUE TITLE
Memory Management

### ISSUE THREAD

**Issue by chland** [llbit/chunky#491]
While playing around with the Hermitcraft 5 world I noticed two minor problems.

When I tried creating a new scene with a LOT of chunks (30k) I noticed that Chunky doesn't seem to handle it very well when it runs out of memory. The first ~16000 chunks or so loaded normally but then, chunky pretty much stopped working. The status-text wasn't updated and the whole app pretty much froze.

After waiting quite some time, an exception showed up in the debug-window (java.lang.OutOfMemoryError: Java heap space) and i decided to kill the process after waiting for another 5-10 minutes (CPU usage was always around 30% - so apparently, Java was doing "something").

I don't know if Chunky really crashed or had some kind of hiccup and would have eventually started working again but I guess it would be nice if it really ran out of memory if it would show a proper error and return to the main screen.

Which brings me to the second thing i encountered (which might be related to Java's garbage collector - but i'm not sure). I was wondering: when does Chunky free the memory it allocates? Personally, I would expect chunky to free it when I close the Render Controls & Render Preview window. But apparently this is not when it happens. I rendered a scene where chunky allocated ~12GB of RAM and when I returned to the main-screen it still stayed at 12GB. I then cleared my selection, selected a few chunk and created a new scene and the allocated memory stayed at 12GB. Chunky then started to load the new chunks but was unbelievable slow and the allocated memory started to drop. It looked like Chunky was loading the chunks and at the same time freeing old memory which caused it to slow down.

**Comment by chland** [comment]
At least some of the problems seem to be related to my JVM-arguments.

IDK why, but for whatever reason I had these arguments:

`-XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000`

After removing the arguemnts it reacts differently (still gets stuck upon loading too many chunks but behaves differently). I will investigate a bit more. Until then, you can basically just ignore this issue :)

**Comment by llbit** [comment]
When a Java program runs out of memory you typically get everything running much slower. This is caused by the Java runtime (JVM). Essentially what happens is that the JVM is trying to repeatedly free up space on the heap for new allocations but failing. Each sweep takes a lot of CPU time so your JVM ends up doing mostly sweeps until it eventually gives up.

Chunky does not really deallocate memory directly, instead it relies on the Java garbage collector to free up memory which there are no references to. The current scene is still kept in memory after you close the render controls window. There is really no reason why, so this could be improved by making sure that that reference is removed when the user closes the render controls window.
