### ISSUE TITLE
chunky won't launch

### ISSUE THREAD

**Issue by joefy200** [llbit/chunky#517]
Every time I try to launch chunky nothing happens. Not even a screen pops up. Just nothing. I got the latest java update and also the latest version of Chunky,

**Comment by llbit** [comment]
If Java was installed or reinstalled **after** Chunky then that can prevent Chunky from launching. Try reinstalling Chunky and see if that helps.

**Comment by llbit** [comment]
We talked about this issue on Discord:

* There was a problem with the Java installation which gave this error: `Error: could not find java.dll`
* This issue was fixed by re-installing Java and using `cmd.exe` to start Chunky.
* The Chunky shortcut still did not work (probably because it pointed to the wrong Java installation).
